name: "Basic Workflow"
on:
  workflow_dispatch:
    inputs:
      app-name:
        description: "Select App Name"
        type: string
        default: ""
        required: true

jobs:
  basic-job:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Basic Step"
        run: echo "Hello, \"${{ github.event.inputs.app-name }}\""
