name: "Basic Action"

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Provide App's Name"
        type: string
        required: true
        default: ""

jobs:
  job:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Basic Step"
        run: "echo \"${{ github.event.inputs.app_name }}\""
